### ISSUE TITLE
www.html5rocks.is down

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/html5rocks#871]
```
Please describe the issue:
1) visiting www.html5rocks.com in Chrome

Please provide any additional information below.
updates.html5rocks.com works well.
The error information shown is:
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 701, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/html5rocks/v20120418.358301048824333647/main.py", line 400, in get
    for r in result:
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2080, in __iter__
    return self.run()
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2061, in run
    raw_query = self._get_query()
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2440, in _get_query
    projection=self._projection,
AttributeError: 'Query' object has no attribute '_projection'


(See attached img)

```

Original issue reported on code.google.com by `Hanrui....@gmail.com` on 19 Apr 2012 at 1:04

Attachments:
- [screenshot_html5rocks.png](https://storage.googleapis.com/google-code-attachments/html5rocks/issue-871/comment-0/screenshot_html5rocks.png)

**Comment by GoogleCodeExporter** [comment]
Original comment by `ericbidelman@chromium.org` on 25 Apr 2012 at 9:56
- Changed state: **Fixed**
